"""initial schema

Revision ID: 51daa58f2e78
Revises: 
Create Date: 2026-07-03 21:50:28.072455

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51daa58f2e78'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('customer', 'surveyor', 'admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('surveys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin_address', sa.Text(), nullable=False),
    sa.Column('destination_address', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('surveyor_id', sa.UUID(), nullable=True),
    sa.Column('preferred_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'assigned', 'in_progress', 'processing', 'ready_for_review', 'awaiting_customer_approval', 'revision_required', 'approved', 'completed', 'cancelled', name='survey_status', native_enum=False), nullable=False),
    sa.Column('total_volume_estimate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_value_estimate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_surveys_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['surveyor_id'], ['users.id'], name=op.f('fk_surveys_surveyor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    op.create_index(op.f('ix_surveys_customer_id'), 'surveys', ['customer_id'], unique=False)
    op.create_index(op.f('ix_surveys_status'), 'surveys', ['status'], unique=False)
    op.create_index(op.f('ix_surveys_surveyor_id'), 'surveys', ['surveyor_id'], unique=False)
    op.create_table('ai_analysis_runs',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='ai_run_status', native_enum=False), nullable=False),
    sa.Column('request_media_count', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_ai_analysis_runs_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis_runs'))
    )
    op.create_index(op.f('ix_ai_analysis_runs_status'), 'ai_analysis_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_analysis_runs_survey_id'), 'ai_analysis_runs', ['survey_id'], unique=False)
    op.create_table('media',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('media_type', sa.Enum('image', 'video', 'processed_image', 'extracted_frame', name='media_type', native_enum=False), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('processed_url', sa.Text(), nullable=True),
    sa.Column('room_location', sa.String(length=255), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'skipped', name='processing_status', native_enum=False), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('parent_video_id', sa.UUID(), nullable=True),
    sa.Column('blur_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_video_id'], ['media.id'], name=op.f('fk_media_parent_video_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_media_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_parent_video_id'), 'media', ['parent_video_id'], unique=False)
    op.create_index(op.f('ix_media_processing_status'), 'media', ['processing_status'], unique=False)
    op.create_index(op.f('ix_media_survey_id'), 'media', ['survey_id'], unique=False)
    op.create_table('survey_history',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('scheduled', 'assigned', 'in_progress', 'processing', 'ready_for_review', 'awaiting_customer_approval', 'revision_required', 'approved', 'completed', 'cancelled', name='survey_status', native_enum=False), nullable=True),
    sa.Column('to_status', sa.Enum('scheduled', 'assigned', 'in_progress', 'processing', 'ready_for_review', 'awaiting_customer_approval', 'revision_required', 'approved', 'completed', 'cancelled', name='survey_status', native_enum=False), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_survey_history_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_history_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_history'))
    )
    op.create_index(op.f('ix_survey_history_survey_id'), 'survey_history', ['survey_id'], unique=False)
    op.create_table('survey_items',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('room_location', sa.String(length=255), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('depth_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('material', sa.String(length=128), nullable=True),
    sa.Column('fragile', sa.Boolean(), nullable=False),
    sa.Column('needs_disassembly', sa.Boolean(), nullable=False),
    sa.Column('needs_special_handling', sa.Boolean(), nullable=False),
    sa.Column('needs_to_ship', sa.Boolean(), nullable=False),
    sa.Column('packing_difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False), nullable=True),
    sa.Column('lifting_difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'poor', 'damaged', name='item_condition', native_enum=False), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_items_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_items'))
    )
    op.create_index(op.f('ix_survey_items_survey_id'), 'survey_items', ['survey_id'], unique=False)
    op.create_table('item_media',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['survey_items.id'], name=op.f('fk_item_media_item_id_survey_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_item_media_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'media_id', name=op.f('pk_item_media'))
    )
    op.create_table('media_processing_jobs',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('image_resize', 'video_frame_extraction', 'blur_detection', 'duplicate_detection', 'ai_analysis', name='job_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'dead_letter', name='job_status', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_media_processing_jobs_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_processing_jobs'))
    )
    op.create_index(op.f('ix_media_processing_jobs_idempotency_key'), 'media_processing_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_media_processing_jobs_media_id'), 'media_processing_jobs', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_processing_jobs_status'), 'media_processing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_processing_jobs_status'), table_name='media_processing_jobs')
    op.drop_index(op.f('ix_media_processing_jobs_media_id'), table_name='media_processing_jobs')
    op.drop_index(op.f('ix_media_processing_jobs_idempotency_key'), table_name='media_processing_jobs')
    op.drop_table('media_processing_jobs')
    op.drop_table('item_media')
    op.drop_index(op.f('ix_survey_items_survey_id'), table_name='survey_items')
    op.drop_table('survey_items')
    op.drop_index(op.f('ix_survey_history_survey_id'), table_name='survey_history')
    op.drop_table('survey_history')
    op.drop_index(op.f('ix_media_survey_id'), table_name='media')
    op.drop_index(op.f('ix_media_processing_status'), table_name='media')
    op.drop_index(op.f('ix_media_parent_video_id'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_ai_analysis_runs_survey_id'), table_name='ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_runs_status'), table_name='ai_analysis_runs')
    op.drop_table('ai_analysis_runs')
    op.drop_index(op.f('ix_surveys_surveyor_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_status'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_customer_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
